name: Build
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@vue-spa
    - name: Use Node.js
      uses: actions/setup-node@vue-spa
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run build